### ISSUE TITLE
Improving Logic for onBackPressed in solutions page

### ISSUE THREAD

**Issue by kshitijsuri90** [immadisairaj/Quiz#23]
On pressing the back button on the solution page the app should take the user back to the home page instead of quitting the application.

**Comment by kshitijsuri90** [comment]
Confirm issues @immadisairaj  so I can start working on it

**Comment by immadisairaj** [comment]
On pressing the back button on the solution page is taking to the quiz activity instead it can be home activity

**Comment by shaliniv16** [comment]
@immadisairaj on pressing the back button on the solution page instead of home screen can it open new quiz?

**Comment by immadisairaj** [comment]
> @immadisairaj on pressing the back button on the solution page instead of home screen can it open new quiz?

No, it would be better if it is home screen. As new quiz comes from home screen right

**Comment by shalini168960** [comment]
> > @immadisairaj on pressing the back button on the solution page instead of home screen can it open new quiz?
> 
> No, it would be better if it is home screen. As new quiz comes from home screen right
Can I work on this issue? @immadisairaj

**Comment by shalini168960** [comment]
Can I work on this issue? @immadisairaj

**Comment by nikelbane** [comment]
I'm a first timer here.....so is this issue resolved?

**Comment by immadisairaj** [comment]
@nikkbann01 this issue is not solved. You can work on this if you wish.
