### ISSUE TITLE
Adding features like category and difficulty level

### ISSUE THREAD

**Issue by Abhi1code** [immadisairaj/Quiz#32]

**Comment by immadisairaj** [comment]
These can be done after the Home Screen is done

**Comment by Abhi1code** [comment]
I can do that too

**Comment by Abhi1code** [comment]
It will be more convenient for me if features are designed with home screen

**Comment by ayush251196** [comment]
Can I work on this?

**Comment by Abhi1code** [comment]
I have almost resolved this issue
