### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by immadisairaj** [immadisairaj/Quiz#48]
When the difficulty is set to hard and category to politics, arts, celebrities, ... the app crashes. When checked the API the response code is 1. So this means there are not enough questions. So the questions have to be reduced based on that.
Can get the number of questions present through the URL
_https://opentdb.com/api_count.php?category=CATEGORY_ID_HERE_

**Comment by Miftahunajat** [comment]
Is the bug still happening ? @immadisairaj

**Comment by immadisairaj** [comment]
@Miftahunajat yeah the bug is still happening. you can work on this if you wish to.
